// Generated by gencpp from file servo_control/HandGraspResponse.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_MESSAGE_HANDGRASPRESPONSE_H
#define SERVO_CONTROL_MESSAGE_HANDGRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control
{
template <class ContainerAllocator>
struct HandGraspResponse_
{
  typedef HandGraspResponse_<ContainerAllocator> Type;

  HandGraspResponse_()
    : value(0)  {
    }
  HandGraspResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int16_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::servo_control::HandGraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control::HandGraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HandGraspResponse_

typedef ::servo_control::HandGraspResponse_<std::allocator<void> > HandGraspResponse;

typedef boost::shared_ptr< ::servo_control::HandGraspResponse > HandGraspResponsePtr;
typedef boost::shared_ptr< ::servo_control::HandGraspResponse const> HandGraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control::HandGraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control::HandGraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'servo_control': ['/home/zhong/version_1_hand/version1_ws/src/servo_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::HandGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::HandGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::HandGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::HandGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::HandGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::HandGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control::HandGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55daaea9ec64e37c8a6144d42a7265e2";
  }

  static const char* value(const ::servo_control::HandGraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55daaea9ec64e37cULL;
  static const uint64_t static_value2 = 0x8a6144d42a7265e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control::HandGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control/HandGraspResponse";
  }

  static const char* value(const ::servo_control::HandGraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control::HandGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 value\n\
\n\
";
  }

  static const char* value(const ::servo_control::HandGraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control::HandGraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandGraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control::HandGraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control::HandGraspResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_MESSAGE_HANDGRASPRESPONSE_H
