// Generated by gencpp from file servo_control/HandGrasp.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_MESSAGE_HANDGRASP_H
#define SERVO_CONTROL_MESSAGE_HANDGRASP_H

#include <ros/service_traits.h>


#include <servo_control/HandGraspRequest.h>
#include <servo_control/HandGraspResponse.h>


namespace servo_control
{

struct HandGrasp
{

typedef HandGraspRequest Request;
typedef HandGraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HandGrasp
} // namespace servo_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servo_control::HandGrasp > {
  static const char* value()
  {
    return "cf5c0ef86653d32d0c3b79408c84d0f3";
  }

  static const char* value(const ::servo_control::HandGrasp&) { return value(); }
};

template<>
struct DataType< ::servo_control::HandGrasp > {
  static const char* value()
  {
    return "servo_control/HandGrasp";
  }

  static const char* value(const ::servo_control::HandGrasp&) { return value(); }
};


// service_traits::MD5Sum< ::servo_control::HandGraspRequest> should match 
// service_traits::MD5Sum< ::servo_control::HandGrasp > 
template<>
struct MD5Sum< ::servo_control::HandGraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servo_control::HandGrasp >::value();
  }
  static const char* value(const ::servo_control::HandGraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_control::HandGraspRequest> should match 
// service_traits::DataType< ::servo_control::HandGrasp > 
template<>
struct DataType< ::servo_control::HandGraspRequest>
{
  static const char* value()
  {
    return DataType< ::servo_control::HandGrasp >::value();
  }
  static const char* value(const ::servo_control::HandGraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servo_control::HandGraspResponse> should match 
// service_traits::MD5Sum< ::servo_control::HandGrasp > 
template<>
struct MD5Sum< ::servo_control::HandGraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servo_control::HandGrasp >::value();
  }
  static const char* value(const ::servo_control::HandGraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_control::HandGraspResponse> should match 
// service_traits::DataType< ::servo_control::HandGrasp > 
template<>
struct DataType< ::servo_control::HandGraspResponse>
{
  static const char* value()
  {
    return DataType< ::servo_control::HandGrasp >::value();
  }
  static const char* value(const ::servo_control::HandGraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVO_CONTROL_MESSAGE_HANDGRASP_H
