// Generated by gencpp from file servo_control/SetTorque.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_MESSAGE_SETTORQUE_H
#define SERVO_CONTROL_MESSAGE_SETTORQUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control
{
template <class ContainerAllocator>
struct SetTorque_
{
  typedef SetTorque_<ContainerAllocator> Type;

  SetTorque_()
    : id(0)
    , ptorque(0)
    , ptime(0)
    , otorque(0)  {
    }
  SetTorque_(const ContainerAllocator& _alloc)
    : id(0)
    , ptorque(0)
    , ptime(0)
    , otorque(0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef int16_t _ptorque_type;
  _ptorque_type ptorque;

   typedef int16_t _ptime_type;
  _ptime_type ptime;

   typedef int16_t _otorque_type;
  _otorque_type otorque;




  typedef boost::shared_ptr< ::servo_control::SetTorque_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control::SetTorque_<ContainerAllocator> const> ConstPtr;

}; // struct SetTorque_

typedef ::servo_control::SetTorque_<std::allocator<void> > SetTorque;

typedef boost::shared_ptr< ::servo_control::SetTorque > SetTorquePtr;
typedef boost::shared_ptr< ::servo_control::SetTorque const> SetTorqueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control::SetTorque_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control::SetTorque_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'servo_control': ['/home/zhong/version_1_hand/version1_ws/src/servo_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::SetTorque_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::SetTorque_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::SetTorque_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::SetTorque_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::SetTorque_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::SetTorque_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control::SetTorque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "323a0bff3fb4a0ad827682d128ae9b5c";
  }

  static const char* value(const ::servo_control::SetTorque_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x323a0bff3fb4a0adULL;
  static const uint64_t static_value2 = 0x827682d128ae9b5cULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control::SetTorque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control/SetTorque";
  }

  static const char* value(const ::servo_control::SetTorque_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control::SetTorque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n\
int16 ptorque\n\
int16 ptime\n\
int16 otorque\n\
";
  }

  static const char* value(const ::servo_control::SetTorque_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control::SetTorque_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.ptorque);
      stream.next(m.ptime);
      stream.next(m.otorque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTorque_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control::SetTorque_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control::SetTorque_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "ptorque: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ptorque);
    s << indent << "ptime: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ptime);
    s << indent << "otorque: ";
    Printer<int16_t>::stream(s, indent + "  ", v.otorque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_MESSAGE_SETTORQUE_H
