// Generated by gencpp from file servo_control/WritePos.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_MESSAGE_WRITEPOS_H
#define SERVO_CONTROL_MESSAGE_WRITEPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control
{
template <class ContainerAllocator>
struct WritePos_
{
  typedef WritePos_<ContainerAllocator> Type;

  WritePos_()
    : id(0)
    , pos(0)
    , exe_time(0)  {
    }
  WritePos_(const ContainerAllocator& _alloc)
    : id(0)
    , pos(0)
    , exe_time(0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef int16_t _pos_type;
  _pos_type pos;

   typedef int32_t _exe_time_type;
  _exe_time_type exe_time;




  typedef boost::shared_ptr< ::servo_control::WritePos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control::WritePos_<ContainerAllocator> const> ConstPtr;

}; // struct WritePos_

typedef ::servo_control::WritePos_<std::allocator<void> > WritePos;

typedef boost::shared_ptr< ::servo_control::WritePos > WritePosPtr;
typedef boost::shared_ptr< ::servo_control::WritePos const> WritePosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control::WritePos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control::WritePos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'servo_control': ['/home/zhong/version_1_hand/version1_ws/src/servo_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::WritePos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::WritePos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::WritePos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::WritePos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::WritePos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::WritePos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control::WritePos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5344dbb4eb0d3ece2f045928ac961746";
  }

  static const char* value(const ::servo_control::WritePos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5344dbb4eb0d3eceULL;
  static const uint64_t static_value2 = 0x2f045928ac961746ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control::WritePos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control/WritePos";
  }

  static const char* value(const ::servo_control::WritePos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control::WritePos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n\
int16 pos\n\
int32 exe_time\n\
";
  }

  static const char* value(const ::servo_control::WritePos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control::WritePos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pos);
      stream.next(m.exe_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WritePos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control::WritePos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control::WritePos_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "pos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pos);
    s << indent << "exe_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.exe_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_MESSAGE_WRITEPOS_H
